### PR TITLE
Add SCSS support and default layout

### LINKED ISSUE #2: Shouldn't SASS be processed on build?
Or that's a Netlify thing?

### PR DESCRIPTION
**Pull request by zomars**
fixes #2

### CODE REVIEW

**Comment by juanfrank77** [comment]
@zomars Thank you for doing this!

Looks very thorough, I'm looking at all the changes and testing them in my local repo before merging it but once again appreciate the effort 👍

**Comment by zomars** [comment]
I've noticed that the links in the inbox template are not working properly in my localhost. I see you added netlify redirects to solve it but sadly I'm not using Netlify at all.

**Review by juanfrank77 — APPROVED** [review]
Good job on this.

**Comment by juanfrank77** [comment]
> I've noticed that the links in the inbox template are not working properly in my localhost. I see you added netlify redirects to solve it but sadly I'm not using Netlify at all.

@zomars Yes, initially I wanted to do an as easy as possible setup in case it would have to be done by somebody who didn't know much about code.

But later realized the issue of the fact that 11ty takes the wikilinks and append them to the overall route. For that I had to go digging into the docs to see how the pages get generated at build time. I made the Netlify redirects as a temporary solution but couldn't hack away any further 'cause I got into a new project at work and my spare time has been close to 0.

**Pull request merged**
